# Generated by Django 5.2 on 2025-06-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_run", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="status",
            field=models.CharField(
                choices=[
                    ("init", "init"),
                    ("in_progres", "in_progres"),
                    ("finished", "finished"),
                ],
                default="init",
            ),
        ),
    ]
