# Generated by Django 5.2 on 2025-08-12 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_run", "0006_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_run.run"
            ),
        ),
    ]
