# Generated by Django 5.2 on 2025-07-22 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_run", "0007_remove_position_run_alter_position_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="run",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="position",
                to="app_run.run",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="position",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
