# Generated by Django 5.2 on 2025-08-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_run", "0007_alter_position_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="distance",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
