# Generated by Django 5.2 on 2025-11-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_run", "0008_run_distance"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectibleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("uid", models.CharField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("picture", models.CharField()),
                ("value", models.IntegerField()),
            ],
        ),
    ]
