# Generated by Django 5.2 on 2025-07-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_run", "0008_position_run_alter_position_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
