# Generated by Django 5.2 on 2025-07-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_run", "0009_alter_position_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
