# Generated by Django 5.2 on 2025-11-29 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_run", "0009_collectibleitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectibleitem",
            name="users",
            field=models.ManyToManyField(
                related_name="collectible_items", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
