# Generated by Django 5.2 on 2025-12-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_run", "0010_collectibleitem_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
