# Generated by Django 5.2 on 2025-12-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_run", "0011_position_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="run_time_seconds",
            field=models.IntegerField(default=0),
        ),
    ]
