# Generated by Django 5.2 on 2025-12-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_run", "0012_run_run_time_seconds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="run_time_seconds",
            field=models.IntegerField(default=None),
        ),
    ]
