# Generated by Django 5.2 on 2025-12-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_run", "0015_alter_run_run_time_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="position",
            name="speed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="run",
            name="speed",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
